In [1]:
import numpy
print(numpy.__version__)
print(numpy.__file__)


1.26.4
C:\ProgramData\anaconda3\Lib\site-packages\numpy\__init__.py


In [2]:
# ==========================================
# SVM CLASSIFICATION USING IRIS DATASET
# ==========================================

# Step 1: Import required libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# ==========================================
# Step 2: Load Iris Dataset
# ==========================================

iris = load_iris()

X = iris.data
y = iris.target

print("Dataset loaded successfully!")
print("Number of samples:", len(X))
print("Number of features:", X.shape[1])

# ==========================================
# Step 3: Split Dataset into Training and Testing
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

# ==========================================
# Step 4: Linear Kernel SVM
# ==========================================

linear_svm = SVC(kernel='linear')

# Train the model
linear_svm.fit(X_train, y_train)

# Make predictions
linear_pred = linear_svm.predict(X_test)

# Calculate accuracy
linear_accuracy = accuracy_score(y_test, linear_pred)

# Confusion Matrix
linear_cm = confusion_matrix(y_test, linear_pred)

print("\n==========================================")
print("        LINEAR KERNEL SVM")
print("==========================================")

print("Accuracy:", linear_accuracy * 100, "%")

print("\nConfusion Matrix:")
print(linear_cm)

# ==========================================
# Step 5: RBF Kernel SVM
# ==========================================

rbf_svm = SVC(kernel='rbf')

# Train the model
rbf_svm.fit(X_train, y_train)

# Make predictions
rbf_pred = rbf_svm.predict(X_test)

# Calculate accuracy
rbf_accuracy = accuracy_score(y_test, rbf_pred)

# Confusion Matrix
rbf_cm = confusion_matrix(y_test, rbf_pred)

print("\n==========================================")
print("          RBF KERNEL SVM")
print("==========================================")

print("Accuracy:", rbf_accuracy * 100, "%")

print("\nConfusion Matrix:")
print(rbf_cm)

# ==========================================
# Step 6: Test Prediction
# ==========================================

print("\n==========================================")
print("          SAMPLE PREDICTION")
print("==========================================")

sample = [[5.1, 3.5, 1.4, 0.2]]

prediction = linear_svm.predict(sample)

print("Input:", sample)
print("Predicted Class:", iris.target_names[prediction[0]])

# ==========================================
# Step 7: Final Result
# ==========================================

print("\n==========================================")
print("SVM was successfully implemented on Iris Dataset")
print("==========================================")

Dataset loaded successfully!
Number of samples: 150
Number of features: 4

Training samples: 120
Testing samples: 30

        LINEAR KERNEL SVM
Accuracy: 100.0 %

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

          RBF KERNEL SVM
Accuracy: 100.0 %

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

          SAMPLE PREDICTION
Input: [[5.1, 3.5, 1.4, 0.2]]
Predicted Class: setosa

SVM was successfully implemented on Iris Dataset
