In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

data = {
    'CGPA': [9.5, 8.0, 8.5, 6.0, 6.5, 8.2, 5.8, 8.9],
    'Assessment': [85, 80, 81, 45, 50, 72, 38, 91],
    'Project': [8, 7, 8.5, 4, 7, 5, 6, 9],
    'Result': ['pass', 'pass', 'pass', 'pass', 'fail', 'pass', 'fail', 'pass']
}

dataset = pd.DataFrame(data)

print(dataset.shape)
print(dataset.head())
print(dataset.tail(2))

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print("Input:")
print(x)

print("Output:")
print(y)

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.20, random_state=0
)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)

print("Actual Output:")
print(y_test)

print("Predicted Output:")
print(y_pred)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

print("Classification Report:")
print(classification_report(y_test, y_pred))

(8, 4)
   CGPA  Assessment  Project Result
0   9.5          85      8.0   pass
1   8.0          80      7.0   pass
2   8.5          81      8.5   pass
3   6.0          45      4.0   pass
4   6.5          50      7.0   fail
   CGPA  Assessment  Project Result
6   5.8          38      6.0   fail
7   8.9          91      9.0   pass
Input:
[[ 9.5 85.   8. ]
 [ 8.  80.   7. ]
 [ 8.5 81.   8.5]
 [ 6.  45.   4. ]
 [ 6.5 50.   7. ]
 [ 8.2 72.   5. ]
 [ 5.8 38.   6. ]
 [ 8.9 91.   9. ]]
Output:
['pass' 'pass' 'pass' 'pass' 'fail' 'pass' 'fail' 'pass']


C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreatePro

Actual Output:
['fail' 'pass']
Predicted Output:
['pass' 'pass']
Accuracy: 0.5
Confusion Matrix:
[[0 1]
 [0 1]]
Classification Report:
              precision    recall  f1-score   support

        fail       0.00      0.00      0.00         1
        pass       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data = {
    'Hours': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    'Attendance': [60, 65, 70, 75, 80, 85, 90, 92, 95, 98],
    'Result': ['fail', 'fail', 'fail', 'pass', 'pass',
               'pass', 'pass', 'pass', 'pass', 'pass']
}

df = pd.DataFrame(data)

X = df[['Hours', 'Attendance']]
y = df['Result']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)


y_pred = knn.predict(X_test)

print("Actual:", y_test.values)
print("Predicted:", y_pred)


print("Accuracy:", accuracy_score(y_test, y_pred))


print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


new_student = [[6, 85]]

result = knn.predict(new_student)

print("New Student Result:", result[0])

Actual: ['pass' 'fail' 'pass']
Predicted: ['pass' 'fail' 'pass']
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 2]]
New Student Result: pass


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [5]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

X = np.array([
    [2, 50],
    [3, 55],
    [4, 60],
    [5, 65],
    [6, 70],
    [7, 75],
    [8, 80],
    [9, 90]
])

y = np.array([0, 0, 0, 1, 1, 1, 1, 1])


model = Sequential()

model.add(Input(shape=(2,)))

model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X, y, epochs=100, verbose=0)

loss, accuracy = model.evaluate(X, y, verbose=0)

print("Accuracy:", accuracy)

new_student = np.array([[6, 72]])

prediction = model.predict(new_student, verbose=0)

print("Prediction probability:", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Result: Pass")
else:
    print("Result: Fail")

Accuracy: 0.625
Prediction probability: 0.7459675
Result: Pass


In [10]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

X = np.array([
    [2, 50],
    [3, 55],
    [4, 60],
    [6, 70],
    [7, 75],
    [8, 80]
])

y = np.array([0, 0, 0, 1, 1, 1])

model = Sequential()

model.add(Input(shape=(2,)))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X, y, epochs=50, verbose=0)

new_student = np.array([[6, 72]])

prediction = model.predict(new_student, verbose=0)

print("Prediction:", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Result: Pass")
else:
    print("Result: Fail")

Prediction: 5.212412e-07
Result: Fail
