In [4]:
import numpy as np
from sklearn.decomposition import PCA

X = np.array([
[[2, 3],
 [3, 5],
 [4, 2],
 [5, 6],
 [6, 7]]
])


pca = PCA(n_components=1)

# Apply PCA
X_pca = pca.fit_transform(X)

X_inverse = pca.inverse_transform(X_pca)

print("Original Dataset:")
print(X)

print("\nTransformed Data:")
print(X_pca)

print("\nReconstructed Data (Inverse Transform):")
print(X_inverse)

print("\nExplained Variance Ratio:")
print(pca.explained_variance_ratio_)

print("\nSingular Values:")
print(pca.singular_values_)

print("\nPrincipal Components:")
print(pca.components_)

print("\nMean of Dataset:")
print(pca.mean_)

ValueError: Found array with dim 3. PCA expected <= 2.

In [5]:
import numpy as np
from sklearn.decomposition import PCA

# Create a simple dataset
X = np.array([
    [2, 3],
    [3, 5],
    [4, 2],
    [5, 6],
    [6, 7]
])

# Create PCA model
pca = PCA(n_components=1)

# Apply PCA
X_pca = pca.fit_transform(X)

# Reconstruct the original data
X_inverse = pca.inverse_transform(X_pca)

# Display results
print("Original Dataset:")
print(X)

print("\nTransformed Data:")
print(X_pca)

print("\nReconstructed Data (Inverse Transform):")
print(X_inverse)

print("\nExplained Variance Ratio:")
print(pca.explained_variance_ratio_)

print("\nSingular Values:")
print(pca.singular_values_)

print("\nPrincipal Components:")
print(pca.components_)

print("\nMean of Dataset:")
print(pca.mean_)

Original Dataset:
[[2 3]
 [3 5]
 [4 2]
 [5 6]
 [6 7]]

Transformed Data:
[[-2.44616519]
 [-0.22940192]
 [-2.1529748 ]
 [ 1.71992293]
 [ 3.10861897]]

Reconstructed Data (Inverse Transform):
[[2.62860932 2.57441077]
 [3.87139068 4.41003979]
 [2.7929803  2.81719212]
 [4.96423835 6.02421182]
 [5.74278135 7.1741455 ]]

Explained Variance Ratio:
[0.8563712]

Singular Values:
[4.82631295]

Principal Components:
[[0.56062881 0.82806723]]

Mean of Dataset:
[4.  4.6]


In [7]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

U, S, VT = np.linalg.svd(A)

print("Original Matrix:")
print(A)

print("\nU Matrix:")
print(U)

print("\nSingular Values:")
print(S)

print("\nV Transpose Matrix:")
print(VT)


Original Matrix:
[[1 2]
 [3 4]]

U Matrix:
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

Singular Values:
[5.4649857  0.36596619]

V Transpose Matrix:
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [8]:
import numpy as np


data = np.array([
    ['High',   'Good',    'Good',    'Yes'],
    ['High',   'Average', 'Good',    'Yes'],
    ['Medium', 'Good',    'Average', 'No'],
    ['High',   'Good',    'Average', 'Yes'],
    ['Low',    'Poor',    'Poor',    'No'],
    ['High',   'Average', 'Average', 'Yes']
])


hypothesis = ['0'] * (len(data[0]) - 1)

for row in data:
    if row[-1] == 'Yes':
        for i in range(len(hypothesis)):
            if hypothesis[i] == '0':
                hypothesis[i] = row[i]
            elif hypothesis[i] != row[i]:
                hypothesis[i] = '?'

print("Final Hypothesis:")
print(hypothesis)

Final Hypothesis:
['High', '?', '?']
